// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqHiC4TNHQgHXmm8ACPqkfWjIFjIo6rU0',
    appId: '1:286663305679:android:8dd97bff39a5b477180aba',
    messagingSenderId: '286663305679',
    projectId: 'boomrideshare',
    storageBucket: 'boomrideshare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzami1GNPAvTj9K3LeT-nA1vvbniX4xY',
    appId: '1:286663305679:ios:ba7ef26306947ed1180aba',
    messagingSenderId: '286663305679',
    projectId: 'boomrideshare',
    storageBucket: 'boomrideshare.appspot.com',
    iosClientId: '286663305679-jtbqcp9hhrhljj8mice1ofomksv3hu7o.apps.googleusercontent.com',
    iosBundleId: 'com.booomridedriver.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOzami1GNPAvTj9K3LeT-nA1vvbniX4xY',
    appId: '1:286663305679:ios:35de89d0b0ddc0a4180aba',
    messagingSenderId: '286663305679',
    projectId: 'boomrideshare',
    storageBucket: 'boomrideshare.appspot.com',
    iosClientId: '286663305679-j86mgpt9dk11lva2sclgteifsd8u80kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomDriver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Q0XGQD3wKaWgnrr1Y7ey1vu33q6oRBg',
    appId: '1:286663305679:web:102df9710fe1d72f180aba',
    messagingSenderId: '286663305679',
    projectId: 'boomrideshare',
    authDomain: 'boomrideshare.firebaseapp.com',
    storageBucket: 'boomrideshare.appspot.com',
    measurementId: 'G-08T383ZV6C',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Q0XGQD3wKaWgnrr1Y7ey1vu33q6oRBg',
    appId: '1:286663305679:web:b844c17c476b4438180aba',
    messagingSenderId: '286663305679',
    projectId: 'boomrideshare',
    authDomain: 'boomrideshare.firebaseapp.com',
    storageBucket: 'boomrideshare.appspot.com',
    measurementId: 'G-L8RPQV331N',
  );

}