// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLuZU5HqcqGAIVT8qZ2VlvY8l6GqdKVk',
    appId: '1:575261100821:android:9a7b40f42e104a3ff8771c',
    messagingSenderId: '575261100821',
    projectId: 'boom-1b98b',
    storageBucket: 'boom-1b98b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6sZ-tayNm0lB7QU2cPdd3ntC4qEIUk2Y',
    appId: '1:575261100821:ios:af0779bc8b6e7412f8771c',
    messagingSenderId: '575261100821',
    projectId: 'boom-1b98b',
    storageBucket: 'boom-1b98b.appspot.com',
    iosBundleId: 'com.example.boomDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6sZ-tayNm0lB7QU2cPdd3ntC4qEIUk2Y',
    appId: '1:575261100821:ios:af0779bc8b6e7412f8771c',
    messagingSenderId: '575261100821',
    projectId: 'boom-1b98b',
    storageBucket: 'boom-1b98b.appspot.com',
    iosBundleId: 'com.example.boomDriver',
  );
}
